development:
  adapter: postgresql
  encoding: unicode
  database: bateponto_development
  username: roger
  password:
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: bateponto_production
  username: roger
  password:
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: bateponto_test
  username: roger
  password:
  pool: 5
